export let products = [
  {
    name: "Fridge",
    about: "Store your foods for long time",
    price: 5000,
    quantity: 100,
    id: 1,
  },
  {
    name: "Microwave oven",
    about: "Cook your foods with ease",
    price: 5000,
    quantity: 100,
    id: 2,
  },
  {
    name: "Laptop",
    about: "Complete your tasks on the Go",
    price: 5000,
    quantity: 100,
    id: 3,
  },
  {
    name: "AC",
    about: "Make your home cooler in summer and worm in winter",
    price: 5000,
    quantity: 100,
    id: 4,
  },
  {
    name: "Television",
    about: "Watch your desired shows sitting on your couch ",
    price: 5000,
    quantity: 100,
    id: 5,
  },
  {
    name: "Sandwitch Maker",
    about: "Make a quick breakfast with this product",
    price: 5000,
    quantity: 100,
    id: 6,
  },
  {
    name: "Washing Machine",
    about: "Wash dirty clothes without getting wet",
    price: 5000,
    quantity: 100,
    id: 7,
  },
  {
    name: "Coffee maker",
    about: "Brew fresh coffee using this fine machine",
    price: 5000,
    quantity: 100,
    id: 8,
  },
  {
    name: "Water purifier",
    about: "Connec to supply water line and get pure drinking water",
    price: 5000,
    quantity: 100,
    id: 9,
  },
];
